stages:
  - build
  - test
  - deploy

# image: docker:latest
image: amazoncorretto:17

build:
  stage: build
  before_script: 
    - chmod +x ./gradlew # gradlew 실행권한 부여
  script:
    - echo "> 프로젝트 Build 시작"
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar # build의 결과물인 jar 파일을 artifacts로 지정
    expire_in: 1 week # 1주일 동안 보관

test:
  stage: test
  script:
    - echo "> 프로젝트 테스트코드 Test 시작"
    - ./gradlew test

deploy-to-server:
  stage: deploy
  before_script:
    # - 'command -v ssh-agent >/dev/null || ( yum update -y && yum install openssh-clients -y )'
    # - eval $(ssh-agent -s)
    # - echo "$SSH_PRIVATE_KEY" | ssh-add -
  script:
    # 원격 스크립트 실행
    # - echo "> 프로젝트 서버 Deploy 시작"
    # - echo "> DEPLOY_SERVER_IP 는 $DEPLOY_SERVER_IP"
    # - ssh ec2-user@"$DEPLOY_SERVER_IP" '~/test/deploy.sh'

